### ISSUE TITLE
[Feature Request] Rules for labelling or moving to folder incoming emails

### ISSUE THREAD

**Issue by Sqwalou** [skiff-org/skiff-apps#42]
Would it be possible to implement rules for incoming emails? Particularly for emails from a specific sender to be automatically moved to a folder or set to a certain label.
Thank you!

**Comment by pfr-dev** [comment]
I litereally just provided the same feedback using the inbuild feedback function:

 - Add corresponding labels to email aliases automatically so that emails are sorted into into label groups based on the alias that is used. 
 
- Further to this, add the option to automatically move emails assigned with a label into another folder, removing the clutter from the inbox. 
 
This feature is a must for anyone who likes to keep a clean (zero) inbox.

**Comment by amilich** [comment]
> I litereally just provided the same feedback using the inbuild feedback function:
> 
> * Add corresponding labels to email aliases automatically so that emails are sorted into into label groups based on the alias that is used.
> * Further to this, add the option to automatically move emails assigned with a label into another folder, removing the clutter from the inbox.
> 
> This feature is a must for anyone who likes to keep a clean (zero) inbox.

We're working on both of these!

**Comment by amilich** [comment]
Complete.
