### ISSUE TITLE
Why is the Skiff Mail not open source (but you falsely call it that)?

### ISSUE THREAD

**Issue by raikasdev** [skiff-org/skiff-apps#93]
Skiff's mail client is not open source. CC-BY-NC-SA is far from an open source license.

You are limiting user's ability to use it commercially. This goes straight against the Open Source Initiative's Open Source Definition's 6th guideline "No Discrimination Against Fields of Endeavor".

Why is this? On your Open Source page you say that "We’re committed to building
open source software", but your products aren't, just few libraries are.

Under the "Open Source" title there is Skiff Apps, which then shows link to "Skiff Mail code". And well, [the license](https://github.com/skiff-org/skiff-apps/tree/main) is CC-BY-NCA-SA. 

On your website you say "**Open-source and audited** Skiff Mail is open-source, uses open-source cryptography, and undergoes external security audits."

![image](https://github.com/skiff-org/skiff-apps/assets/29684625/7693c18b-f26a-44b6-87c1-9728b606b2e4)

I'd say that's false marketing, and even [It's FOSS News](https://news.itsfoss.com/skiff-mail-review/) fell for it.

According to issue #2 this has already been covered. If you decide you want to keep the CC license, please transparently communicate to your users, that the software they use is in fact not open source, but _source-available_. I think it's misleading, when there are actual open source startups doing the hard work and using actual Open Source licenses, and you trying to just use their reputation for Skiff.

Thank you!

**Comment by amilich** [comment]
Hello! Libraries inside the codebase are MIT licensed, including skiff-crypto and skiff-ui. We are not currently going to release other products for commercial use.

**Comment by illiliti** [comment]
Don't lie. Here's an example of library that uses not open-source CC-BY-NC-SA license, but claims to be open-source:

https://github.com/skiff-org/skiff-apps/tree/main/libs/skiff-utils

Do I need to continue?

**Comment by raikasdev** [comment]
On your website you clearly state that the clients are open source, which they are not. Open Source guidelines require open source software to be able to be used commercially.

**Comment by amilich** [comment]
> https://github.com/skiff-org/skiff-apps/tree/main/libs/skiff-utils
> 
> Do I need to continue?

Comments like this are unproductive and unhelpful. I mentioned that `skiff-crypto` and `skiff-ui` are MIT licensed.

Commercial use is not a requirement for open source software. Study the MongoDB case.

**Comment by raikasdev** [comment]
MongoDB is not open source, it's source-available. It was a controversy in the open source community when they decided to walk away from open source to a commercially limiting license.

It. Is. Not. Open. Source.

https://opensource.org/faq/#commercial

And claiming that Skiff's email client is open source is false advertising.

**Comment by illiliti** [comment]
> Comments like this are unproductive and unhelpful.

Of course accusing in such a blatant lie is unhelpful for you. It does not make you look good, that's why you don't like my comment.

> I mentioned that skiff-crypto and skiff-ui are MIT licensed.

Does not matter because as long as there's at least one file licensed under CC-BY-NC-SA this project cannot be open-source.

> Commercial use is not a requirement for open source software.

Commercial use is, in fact, one of ten criterias of open-source software. If you don't comply, your software is not open-source.

> Study the MongoDB case.

MongoDB is source-available software, not open-source. Yours should be too and in fact it is. You are just abusing open-source term for your own shady marketing purposes.

**Comment by amilich** [comment]
Let's all calm down. Skiff Mail is _one year old_. I hope you realize that taking a positive tone and perspective matters a lot with the open-source community. Why not take a positive approach?

Regarding the accusation of false advertising: We strive to be transparent about our licensing. Our project does use a combination of licenses, including CC-BY-NC-SA for certain content, and MIT for the rest. We understand that the inclusion of a Non-Commercial license does not adhere strictly to **some** definitions of open source. However, we plan to put a lot of code in this repository. Some will be MIT licensed, some AGPL, and some may remain CC-BY-NC-SA. How about taking a positive approach instead of commenting on every Tweet, issue, and Reddit post, as you all have done?

Concerning the open-source claim: Open source is a broad and sometimes ambiguously defined term. Clearly, some might object to using this term when a project includes CC-BY-NC-SA licensed material.

We hope this clears up any confusion. Please feel free to contribute to the project or engage in further dialogue if you have additional concerns or suggestions. Thank you for your interest and engagement with our project.

**Comment by illiliti** [comment]
> Skiff Mail is one year old.

This does not give you a right to resort to such vile methods as abusing open-source term for your own gain.

> I hope you realize that taking a positive tone and perspective matters a lot with the open-source community. Why not take a positive approach?

Because there are bad actors that abuse open-source term on *purpose*. You are one of them because of your outright lie.

> We understand that the inclusion of a Non-Commercial license does not adhere strictly to some definitions of open source.

There is only one definition of open-source. Attempt to redefine it is considered as [openwashing](https://openwashing.org/).

> How about taking a positive approach instead of commenting on every Tweet, issue, and Reddit post, as you all have done?

I won't take positive approach until you withdraw your position and remove all false advertising.

> Concerning the open-source claim: Open source is a broad and sometimes ambiguously defined term. Clearly, some might object to using this term when a project includes CC-BY-NC-SA licensed material.

There is only one definition of open source. Do not attempt to gaslight us by telling otherwise.

> We hope this clears up any confusion.

Nothing of what you wrote is in any way useful. Only action to remove all false advertising will clear confusion.

**Comment by amilich** [comment]
Alright, this is beyond the type of conversation we'd like to have here. Thanks!
